const ephemeris: Record<number, Record<number, string>> = {
  1: {
    1: "Marie / Jour de l'An",
    2: "S. Basile",
    3: "Ste Geneviève",
    4: "S. Odilon",
    5: "S. Edouard",
    6: "S. Melaine / Épiphanie",
    7: "S. Raymond",
    8: "S. Lucien",
    9: "S. Alix",
    10: "S. Guillaume",
    11: "S. Paulin",
    12: "Ste Tatiana",
    13: "Ste Yvette",
    14: "Ste Nina",
    15: "S. Rémi",
    16: "S. Marcel",
    17: "Ste Roseline",
    18: "Ste Prisca",
    19: "S. Marius",
    20: "S. Sébastien",
    21: "Ste Agnès",
    22: "S. Vincent",
    23: "S. Barnard",
    24: "S. François de Sales",
    25: "S. Conversion de Paul",
    26: "Ste Paule",
    27: "Ste Angèle",
    28: "S. Thomas d'Aquin",
    29: "S. Gildas",
    30: "Ste Martine",
    31: "Ste Marcelle"
  },
  2: {
    1: "Ste Ella",
    2: "S. Présentation / Chandeleur",
    3: "S. Blaise",
    4: "Ste Véronique",
    5: "Ste Agathe",
    6: "S. Gaston",
    7: "Ste Eugénie",
    8: "Ste Jacqueline",
    9: "Ste Apolline",
    10: "S. Arnaud",
    11: "Notre-Dame de Lourdes",
    12: "S. Félix",
    13: "Ste Béatrice",
    14: "S. Valentin",
    15: "S. Claude",
    16: "Ste Julienne",
    17: "S. Alexis",
    18: "Ste Bernadette",
    19: "S. Gabin",
    20: "Ste Aimée",
    21: "S. Damien",
    22: "Ste Isabelle",
    23: "S. Lazare",
    24: "S. Modeste",
    25: "S. Roméo",
    26: "S. Nestor",
    27: "Ste Honorine",
    28: "S. Romain",
    29: "S. Auguste"
  },
  3: {
    1: "S. Albin",
    2: "S. Charles le Bon",
    3: "S. Guénolé",
    4: "S. Casimir",
    5: "Ste Olive",
    6: "Ste Colette",
    7: "Ste Félicité",
    8: "S. Jean de Dieu",
    9: "Ste Françoise",
    10: "S. Vivien",
    11: "Ste Rosine",
    12: "Ste Justine",
    13: "S. Rodrigue",
    14: "Ste Mathilde",
    15: "Ste Louise",
    16: "Ste Bénédicte",
    17: "S. Patrick",
    18: "S. Cyrille",
    19: "S. Joseph",
    20: "S. Herbert",
    21: "Ste Clémence",
    22: "Ste Léa",
    23: "S. Victorien",
    24: "Ste Catherine de Suède",
    25: "Annonciation",
    26: "S. Larissa",
    27: "S. Habib",
    28: "S. Gontran",
    29: "Ste Gladys",
    30: "S. Amédée",
    31: "S. Benjamin"
  },
  4: {
    1: "S. Hugues",
    2: "Ste Sandrine",
    3: "S. Richard",
    4: "S. Isidore",
    5: "Ste Irene",
    6: "S. Marcellin",
    7: "S. Jean-Baptiste de la Salle",
    8: "Ste Julie",
    9: "S. Gautier",
    10: "S. Fulbert",
    11: "S. Stanislas",
    12: "S. Jules",
    13: "Ste Ida",
    14: "S. Maxime",
    15: "S. Paterne",
    16: "S. Benoît-Joseph",
    17: "S. Anicet",
    18: "S. Parfait",
    19: "Ste Emma",
    20: "S. Odette",
    21: "S. Anselme",
    22: "S. Alexandre",
    23: "S. Georges",
    24: "S. Fidèle",
    25: "S. Marc",
    26: "Ste Alida",
    27: "Ste Zita",
    28: "Ste Valérie",
    29: "Ste Catherine de Sienne",
    30: "S. Robert"
  },
  5: {
    1: "Fête du Travail / S. Joseph",
    2: "S. Boris",
    3: "S. Philippe / S. Jacques",
    4: "S. Sylvain",
    5: "S. Judith",
    6: "Ste Prudence",
    7: "Ste Gisèle",
    8: "Victoire 1945 / S. Désiré",
    9: "S. Pacôme",
    10: "Ste Solange",
    11: "Ste Estelle",
    12: "S. Achille",
    13: "Ste Rolande",
    14: "S. Matthias",
    15: "Ste Denise",
    16: "S. Honoré",
    17: "S. Pascal",
    18: "S. Éric",
    19: "S. Yves",
    20: "S. Bernardin",
    21: "S. Constantin",
    22: "S. Émile",
    23: "S. Didier",
    24: "S. Donatien",
    25: "Ste Sophie",
    26: "S. Bérenger",
    27: "S. Augustin de Cantorbéry",
    28: "S. Germain",
    29: "S. Aymar",
    30: "S. Ferdinand",
    31: "Visitation de la Vierge"
  },
  6: {
    1: "S. Justin",
    2: "Ste Blandine",
    3: "S. Kévin",
    4: "Ste Clotilde",
    5: "S. Igor",
    6: "S. Norbert",
    7: "S. Gilbert",
    8: "S. Médard",
    9: "Ste Diane",
    10: "S. Landry",
    11: "S. Barnabé",
    12: "S. Guy",
    13: "S. Antoine de Padoue",
    14: "S. Élishée",
    15: "Ste Germaine",
    16: "S. Jean-François Régis",
    17: "S. Hervé",
    18: "S. Léonce",
    19: "S. Romuald",
    20: "S. Silvère",
    21: "S. Rodolphe / Été",
    22: "S. Alban",
    23: "Ste Audrey",
    24: "S. Jean-Baptiste / S. Yann Le créateur 👑🤣",
    25: "S. Prosper",
    26: "S. Anthelme",
    27: "S. Fernand",
    28: "S. Irénée",
    29: "S. Pierre / S. Paul",
    30: "S. Martial"
  },
  7: {
    1: "S. Thierry",
    2: "S. Martinien",
    3: "S. Thomas",
    4: "S. Florent",
    5: "S. Antoine-Marie",
    6: "Ste Mariette",
    7: "S. Raoul",
    8: "S. Thibaut",
    9: "Ste Amandine",
    10: "S. Ulrich",
    11: "S. Benoît",
    12: "S. Olivier",
    13: "S. Henri / S. Joël",
    14: "Fête Nationale / S. Camille",
    15: "S. Donald",
    16: "N-D du Mont-Carmel / S. Elpide",
    17: "Ste Charlotte",
    18: "S. Frédéric",
    19: "S. Arsène",
    20: "Ste Marina",
    21: "S. Victor",
    22: "Ste Marie-Madeleine",
    23: "Ste Brigitte",
    24: "Ste Christine",
    25: "S. Jacques",
    26: "Ste Anne / S. Joachim",
    27: "Ste Nathalie",
    28: "S. Samson",
    29: "Ste Marthe",
    30: "Ste Juliette",
    31: "S. Ignace de Loyola"
  },
  8: {
    1: "S. Alphonse",
    2: "S. Julien Eymard",
    3: "Ste Lydie",
    4: "S. Jean-Marie Vianney",
    5: "S. Abel",
    6: "Transfiguration",
    7: "S. Gaétan",
    8: "S. Dominique",
    9: "S. Amour",
    10: "S. Laurent",
    11: "Ste Claire",
    12: "Ste Chantal",
    13: "S. Hippolyte",
    14: "S. Evrard",
    15: "Assomption",
    16: "S. Armel",
    17: "S. Hyacinthe",
    18: "Ste Hélène",
    19: "S. Jean Eudes",
    20: "S. Bernard",
    21: "S. Christophe",
    22: "S. Fabrice",
    23: "Ste Rose de Lima",
    24: "S. Barthélemy",
    25: "S. Louis",
    26: "S. Césaire",
    27: "Ste Monique",
    28: "S. Augustin",
    29: "S. Sabine",
    30: "S. Fiacre",
    31: "S. Aristide"
  },
  9: {
    1: "S. Gilles",
    2: "S. Ingrid",
    3: "S. Grégoire",
    4: "Ste Rosalie",
    5: "S. Raïssa",
    6: "S. Bertrand",
    7: "Ste Reine",
    8: "Nativité de Marie",
    9: "S. Alain",
    10: "Ste Inès",
    11: "S. Adelphe",
    12: "S. Apollinaire",
    13: "S. Aimé",
    14: "Sainte Croix",
    15: "S. Roland",
    16: "Ste Edith",
    17: "S. Renaud",
    18: "Ste Nadège",
    19: "S. Émilie",
    20: "S. Davy",
    21: "S. Matthieu",
    22: "S. Maurice",
    23: "S. Constant / Automne",
    24: "Ste Thècle",
    25: "S. Hermann",
    26: "S. Côme / S. Damien",
    27: "S. Vincent de Paul",
    28: "S. Venceslas",
    29: "S. Michel / S. Gabriel / S. Raphaël",
    30: "S. Jérôme"
  },
  10: {
    1: "Ste Thèrése de l'Enfant-Jésus",
    2: "Saints Anges Gardiens",
    3: "S. Gérard",
    4: "S. François d'Assise",
    5: "Ste Fleur",
    6: "S. Bruno",
    7: "S. Serge",
    8: "Ste Pélagie",
    9: "S. Denis",
    10: "S. Ghislain",
    11: "S. Firmin",
    12: "S. Wilfrid",
    13: "S. Géraud",
    14: "S. Juste",
    15: "Ste Thérèse d'Avila",
    16: "Ste Edwige / Ste Marguerite",
    17: "S. Baudouin",
    18: "S. Luc",
    19: "S. René Goupil",
    20: "Ste Adeline",
    21: "Ste Céline",
    22: "S. Élodie",
    23: "S. Jean de Capistran",
    24: "S. Florentin",
    25: "S. Crépin",
    26: "S. Dimitri",
    27: "Ste Émeline",
    28: "S. Jude",
    29: "S. Narcisse",
    30: "S. Bienvenu",
    31: "S. Quentin"
  },
  11: {
    1: "Toussaint",
    2: "Défunts",
    3: "S. Hubert",
    4: "S. Charles Borromée",
    5: "Ste Sylvie",
    6: "S. Bertille",
    7: "Ste Carine",
    8: "S. Geoffroy",
    9: "S. Théodore",
    10: "S. Léon",
    11: "Armistice 1918 / S. Martin",
    12: "S. Christian",
    13: "S. Brice",
    14: "S. Sidoine",
    15: "S. Albert",
    16: "Ste Marguerite",
    17: "Ste Élisabeth",
    18: "Ste Aude",
    19: "S. Tanguy",
    20: "S. Edmond",
    21: "Présentation de Marie",
    22: "Ste Cécile",
    23: "S. Clément",
    24: "Ste Flora",
    25: "Ste Catherine",
    26: "Ste Delphine",
    27: "S. Séverin",
    28: "S. Jacob",
    29: "S. Saturnin",
    30: "S. André"
  },
  12: {
    1: "Ste Florence",
    2: "Ste Viviane",
    3: "S. François-Xavier",
    4: "Ste Barbe",
    5: "S. Gérald",
    6: "S. Nicolas",
    7: "S. Ambroise",
    8: "Immaculée Conception",
    9: "S. Pierre Fourier",
    10: "S. Romaric",
    11: "S. Daniel",
    12: "Ste Jeanne-Françoise",
    13: "Ste Lucie",
    14: "S. Jean de la Croix",
    15: "Ste Ninon",
    16: "Ste Alice",
    17: "S. Gaël",
    18: "S. Gatien",
    19: "S. Urbain",
    20: "S. Théophile",
    21: "S. Pierre Canisius / Hiver",
    22: "S. Françoise-Xavière",
    23: "S. Armand",
    24: "Ste Adèle",
    25: "Noël",
    26: "S. Étienne",
    27: "S. Jean",
    28: "Saints Innocents",
    29: "S. David",
    30: "S. Roger",
    31: "S. Sylvestre"
  }
};

/**
 * Returns the traditional saint of the day for a given date.
 */
export function getSaintDuJour(date: Date = new Date()): string {
  try {
    // Standard format converter to Europe/Paris timezone
    const parisFormatter = new Intl.DateTimeFormat('fr-FR', {
      timeZone: 'Europe/Paris',
      day: 'numeric',
      month: 'numeric',
    });
    const parts = parisFormatter.formatToParts(date);
    let day = date.getDate();
    let month = date.getMonth() + 1;
    
    parts.forEach(p => {
      if (p.type === 'day') day = parseInt(p.value, 10);
      if (p.type === 'month') month = parseInt(p.value, 10);
    });

    return ephemeris[month]?.[day] || '';
  } catch {
    // fallback
    const m = date.getMonth() + 1;
    const d = date.getDate();
    return ephemeris[m]?.[d] || '';
  }
}
