/**
 * Morning brief — factual layer ("l'ancre").
 *
 * Deliberately NOT generated by the LLM. The anchor carries numbers the user
 * will act on (what to wear, whether to take an umbrella); a hallucinated
 * temperature would be worse than no brief at all. The model only ever writes
 * the punchline, which carries no factual weight.
 *
 * Output shape is always three segments: `24° · averses dès 15h · parapluie`
 */

export interface MorningAnchorInput {
  tempMax?: number;
  tempMin?: number;
  weatherCode: number;
  uvMax?: number;
  windGustsMax?: number;
  precipSum?: number;
  /** Paris hour (0-23) at which meaningful precipitation starts today, if any. */
  rainStartsAtHour?: number | null;
  /** True when precipitation is spread across most of the day. */
  rainAllDay?: boolean;
}

export interface HourSample {
  hour: number;
  precipProb: number;
  precip: number;
}

/**
 * Finds when rain meaningfully starts during the remaining day, and whether
 * it's a passing shower or a wash-out. "Meaningful" deliberately requires real
 * accumulation or high probability — a 15% chance at 0mm should never put
 * "parapluie" in front of someone at 7am.
 */
export function analyzeRainTiming(hours: HourSample[]): { startsAtHour: number | null; allDay: boolean } {
  const daytime = hours.filter(h => h.hour >= 7 && h.hour <= 22);
  if (daytime.length === 0) return { startsAtHour: null, allDay: false };

  const isWet = (h: HourSample) => h.precip >= 0.2 || h.precipProb >= 55;
  const wet = daytime.filter(isWet);
  if (wet.length === 0) return { startsAtHour: null, allDay: false };

  return {
    startsAtHour: wet[0].hour,
    allDay: wet.length >= Math.max(6, daytime.length * 0.6),
  };
}

const STORM_CODES = [95, 96, 99];
const SNOW_CODES = [71, 73, 75, 77, 85, 86];
const FOG_CODES = [45, 48];
const DRIZZLE_CODES = [51, 53, 55];
const SHOWER_CODES = [80, 81, 82];

function formatHour(h: number): string {
  return `${h}h`;
}

export function buildMorningAnchor(input: MorningAnchorInput): string {
  const {
    tempMax, tempMin, weatherCode, uvMax, windGustsMax,
    rainStartsAtHour, rainAllDay,
  } = input;

  const tempPart =
    typeof tempMax === 'number' ? `${Math.round(tempMax)}°`
    : typeof tempMin === 'number' ? `${Math.round(tempMin)}°`
    : '—';

  let event = '';
  let action = '';

  const hasRainTiming = typeof rainStartsAtHour === 'number';

  if (STORM_CODES.includes(weatherCode)) {
    event = hasRainTiming ? `orages dès ${formatHour(rainStartsAtHour!)}` : 'risque d\'orage';
    action = 'prudence';
  } else if (SNOW_CODES.includes(weatherCode)) {
    event = 'neige';
    action = 'route prudente';
  } else if (typeof windGustsMax === 'number' && windGustsMax >= 60) {
    event = `rafales ${Math.round(windGustsMax)} km/h`;
    action = 'attention aux objets';
  } else if (rainAllDay) {
    event = 'pluie toute la journée';
    action = 'parapluie';
  } else if (hasRainTiming) {
    const isShower = SHOWER_CODES.includes(weatherCode) || DRIZZLE_CODES.includes(weatherCode);
    event = `${isShower ? 'averses' : 'pluie'} dès ${formatHour(rainStartsAtHour!)}`;
    action = 'parapluie';
  } else if (typeof tempMin === 'number' && tempMin <= 0) {
    event = 'gel ce matin';
    action = 'manteau';
  } else if (typeof tempMax === 'number' && tempMax >= 32) {
    event = 'forte chaleur';
    action = 'hydratation';
  } else if (typeof uvMax === 'number' && uvMax >= 7) {
    event = 'UV fort';
    action = 'crème solaire';
  } else if (FOG_CODES.includes(weatherCode)) {
    event = 'brouillard';
    action = 'route prudente';
  } else if (typeof tempMax === 'number' && tempMax <= 8) {
    event = 'journée froide';
    action = 'manteau';
  } else if (weatherCode === 0 || weatherCode === 1) {
    event = 'grand soleil';
    action = typeof uvMax === 'number' && uvMax >= 5 ? 'casquette' : 'profites-en';
  } else {
    event = 'sec toute la journée';
    action = 'rien à prévoir';
  }

  return `${tempPart} · ${event} · ${action}`;
}
